# Generated by Django 4.2.16 on 2024-09-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaseAgreement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='last_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
